### PR TITLE
Add Bicep support to aks-store-demo

### PR DESCRIPTION
**Pull request by dotnet-7**
Add Bicep support to aks-store-demo.

1. Move tf files to /infra/terraform
2. Put bicep files in /infra/bicep
3. Update azure.yaml to use terraform by default
4. Add new azure-bicep.yaml file to root of repo.
5. Add readme note that they need to rename the azure-bicep.yaml file to azure.yaml to use bicep.

**The reason why keyvault is not used in the code to get keys:**
Because the source code to deploy is in the remote images, we cannot directly modify the local code to read key from keyvault. Therefore, we added a command to use 'az' to obtain the keys from the keyvault in the file `azd-hooks/postprovision.sh`.
 
image
**The reason why update `openai_model_capacity` from 120 to 30:**
The capacity of the current OpenAi model is 120 and is too huge for most of the avaliable locations, so we change it to 30 temporarily like other templates.

@jongio for notification.

### CODE REVIEW

**Comment by pauldotyu** [comment]
Thanks for the PR, @dotnet-7. We've just merged in some pretty significant changes to the Terraform templates in PR #96 and PR #104 so there might be some additional resources that need to be added to the Bicep (i.e., ACR and onboarding the AKS cluster to Container Insights and managed Prometheus with managed Grafana). I'll help get conflicts resolved and up to date with latest then review the PR.

**Comment by dotnet-7** [comment]
@pauldotyu, @jongio  - We have resolved the conflicts. PR is ready, please review. Thanks!

**Review by pauldotyu — APPROVED** [review]
Tested this PR and added some fixes. Thanks for your contribution @dotnet-7

**Comment by pauldotyu** [comment]
This resolves #98

**Pull request merged**
